version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: payments_sensor_db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: admin!@#123
    volumes:
      - type: bind
        source: c:/payments_sensor/data
        target: /var/opt/mssql/data
    networks:
      payments_sensor_network:
    ports:
      - 1434:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P admin!@#123 -Q "SELECT Count(*) From PaymentsEmailDB.model.UserLevels" || exit 1
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 30s

  paymentsemail_scannerconfig_webapp:
    image: kparginos/paymentsemailscannerconfigapp:1.0.1
    restart: always
    container_name: paymentsemail_scannerconfig_webapp
    networks:
      - payments_sensor_network
    ports:
      - 7575:80
    depends_on:
      db:
        condition: service_healthy

  paymentsemail_scanner_webapp:
    image: kparginos/paymentsemailscannerwebapp:1.0.1
    restart: always
    container_name: paymentsemail_scanner_webapp
    volumes:
      - type: bind
        source: c:/payments_sensor/logs
        target: /app/logs
      - type: bind
        source: c:/payments_sensor/attachments
        target: /app/attachments
    networks:
      - payments_sensor_network
    ports:
      - 8585:80
    depends_on:
      db:
        condition: service_healthy

networks:
  payments_sensor_network:
